name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: mash
        run: |
          # Setup SSH
          sudo apt-get update -y && sudo apt-get install -y openssh-client
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Deploy static files
          ssh -o StrictHostKeyChecking=no -p22 ubuntu@51.195.219.163 "
           sudo -u mash bash -c '
            # Set up environment
            cd ~/htdocs/$APP_NAME.curato.io/
            export NVM_DIR=\"\$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"
          
            # Set Git credentials for this session (GitHub)
            git config credential.helper \"store --file=/tmp/git-credentials-$$\"
            echo \"https://${GITHUB_TOKEN}@github.com\" > /tmp/git-credentials-$$
          
            # Check if git repository exists, if not clone it
            if [ ! -d .git ]; then
              echo \"Repository not found. Cloning fresh copy...\"
              rm -rf * .[^.]*
              git clone https://${GITHUB_TOKEN}@github.com/DigitallyTailored/mash.git .
            else
              echo \"Repository exists. Updating...\"
              git remote set-url origin https://${GITHUB_TOKEN}@github.com/DigitallyTailored/mash.git
              git pull origin main
            fi
          
            # Install dependencies and build
            npm ci --cache .npm
            npm run build
          
            # The built files are now in dist/ folder
            echo \"Build completed. Files are in dist/ directory\"
            ls -la dist/
          
            # Clean up credentials
            rm -f /tmp/git-credentials-$$
           '
          "
